/* A Bison parser, made by GNU Bison 3.8.2.  */

/* Bison implementation for Yacc-like parsers in C

   Copyright (C) 1984, 1989-1990, 2000-2015, 2018-2021 Free Software Foundation,
   Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* C LALR(1) parser skeleton written by Richard Stallman, by
   simplifying the original so-called "semantic" parser.  */

/* DO NOT RELY ON FEATURES THAT ARE NOT DOCUMENTED in the manual,
   especially those whose name start with YY_ or yy_.  They are
   private implementation details that can be changed or removed.  */

/* All symbols defined below should begin with yy or YY, to avoid
   infringing on user name space.  This should be done even for local
   variables, as they might otherwise be expanded by user macros.
   There are some unavoidable exceptions within include files to
   define necessary library symbols; they are noted "INFRINGES ON
   USER NAME SPACE" below.  */

/* Identify Bison output, and Bison version.  */
#define YYBISON 30802

/* Bison version string.  */
#define YYBISON_VERSION "3.8.2"

/* Skeleton name.  */
#define YYSKELETON_NAME "yacc.c"

/* Pure parsers.  */
#define YYPURE 0

/* Push parsers.  */
#define YYPUSH 0

/* Pull parsers.  */
#define YYPULL 1




/* First part of user prologue.  */
#line 1 "/root/calculator/frontend/flexbison/Calculator.y"

#include <cstdio>
#include <cstring>

// 词法分析头文件
#include "FlexLexer.h"

// bison生成的头文件
#include "BisonParser.h"

// 抽象语法树函数定义原型头文件
#include "AST.h"

// LR分析失败时所调用函数的原型声明
void yyerror(char * msg);


#line 89 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"

# ifndef YY_CAST
#  ifdef __cplusplus
#   define YY_CAST(Type, Val) static_cast<Type> (Val)
#   define YY_REINTERPRET_CAST(Type, Val) reinterpret_cast<Type> (Val)
#  else
#   define YY_CAST(Type, Val) ((Type) (Val))
#   define YY_REINTERPRET_CAST(Type, Val) ((Type) (Val))
#  endif
# endif
# ifndef YY_NULLPTR
#  if defined __cplusplus
#   if 201103L <= __cplusplus
#    define YY_NULLPTR nullptr
#   else
#    define YY_NULLPTR 0
#   endif
#  else
#   define YY_NULLPTR ((void*)0)
#  endif
# endif

#include "CalculatorBison.h"
/* Symbol kind.  */
enum yysymbol_kind_t
{
  YYSYMBOL_YYEMPTY = -2,
  YYSYMBOL_YYEOF = 0,                      /* "end of file"  */
  YYSYMBOL_YYerror = 1,                    /* error  */
  YYSYMBOL_YYUNDEF = 2,                    /* "invalid token"  */
  YYSYMBOL_T_DIGIT = 3,                    /* T_DIGIT  */
  YYSYMBOL_T_ID = 4,                       /* T_ID  */
  YYSYMBOL_T_FUNC = 5,                     /* T_FUNC  */
  YYSYMBOL_T_RETURN = 6,                   /* T_RETURN  */
  YYSYMBOL_T_ADD = 7,                      /* T_ADD  */
  YYSYMBOL_T_SUB = 8,                      /* T_SUB  */
  YYSYMBOL_T_MUL = 9,                      /* T_MUL  */
  YYSYMBOL_T_DIV = 10,                     /* T_DIV  */
  YYSYMBOL_T_MOD = 11,                     /* T_MOD  */
  YYSYMBOL_T_VOID = 12,                    /* T_VOID  */
  YYSYMBOL_T_INT = 13,                     /* T_INT  */
  YYSYMBOL_T_LE = 14,                      /* T_LE  */
  YYSYMBOL_T_LT = 15,                      /* T_LT  */
  YYSYMBOL_T_GT = 16,                      /* T_GT  */
  YYSYMBOL_T_GE = 17,                      /* T_GE  */
  YYSYMBOL_T_NE = 18,                      /* T_NE  */
  YYSYMBOL_T_EQ = 19,                      /* T_EQ  */
  YYSYMBOL_T_AND = 20,                     /* T_AND  */
  YYSYMBOL_T_NOT = 21,                     /* T_NOT  */
  YYSYMBOL_T_IF = 22,                      /* T_IF  */
  YYSYMBOL_T_ELSE = 23,                    /* T_ELSE  */
  YYSYMBOL_T_WHILE = 24,                   /* T_WHILE  */
  YYSYMBOL_25_ = 25,                       /* '('  */
  YYSYMBOL_26_ = 26,                       /* ')'  */
  YYSYMBOL_27_ = 27,                       /* ';'  */
  YYSYMBOL_28_ = 28,                       /* ','  */
  YYSYMBOL_29_ = 29,                       /* '{'  */
  YYSYMBOL_30_ = 30,                       /* '}'  */
  YYSYMBOL_31_ = 31,                       /* '='  */
  YYSYMBOL_32_ = 32,                       /* '['  */
  YYSYMBOL_33_ = 33,                       /* ']'  */
  YYSYMBOL_YYACCEPT = 34,                  /* $accept  */
  YYSYMBOL_CompileUnit = 35,               /* CompileUnit  */
  YYSYMBOL_FuncDef = 36,                   /* FuncDef  */
  YYSYMBOL_FuncFormalParams = 37,          /* FuncFormalParams  */
  YYSYMBOL_FuncFormalParam = 38,           /* FuncFormalParam  */
  YYSYMBOL_FuncBasicParam = 39,            /* FuncBasicParam  */
  YYSYMBOL_IfStatement = 40,               /* IfStatement  */
  YYSYMBOL_WhileStatement = 41,            /* WhileStatement  */
  YYSYMBOL_Block = 42,                     /* Block  */
  YYSYMBOL_BlockItemList = 43,             /* BlockItemList  */
  YYSYMBOL_BlockItem = 44,                 /* BlockItem  */
  YYSYMBOL_Statement = 45,                 /* Statement  */
  YYSYMBOL_VarDecls = 46,                  /* VarDecls  */
  YYSYMBOL_VarDecl = 47,                   /* VarDecl  */
  YYSYMBOL_Array = 48,                     /* Array  */
  YYSYMBOL_Expr = 49,                      /* Expr  */
  YYSYMBOL_AndExp = 50,                    /* AndExp  */
  YYSYMBOL_CmpExp = 51,                    /* CmpExp  */
  YYSYMBOL_AddExp = 52,                    /* AddExp  */
  YYSYMBOL_MulExp = 53,                    /* MulExp  */
  YYSYMBOL_MinusExp = 54,                  /* MinusExp  */
  YYSYMBOL_UnaryExp = 55,                  /* UnaryExp  */
  YYSYMBOL_PrimaryExp = 56,                /* PrimaryExp  */
  YYSYMBOL_LVal = 57,                      /* LVal  */
  YYSYMBOL_RealParamList = 58              /* RealParamList  */
};
typedef enum yysymbol_kind_t yysymbol_kind_t;




#ifdef short
# undef short
#endif

/* On compilers that do not define __PTRDIFF_MAX__ etc., make sure
   <limits.h> and (if available) <stdint.h> are included
   so that the code can choose integer types of a good width.  */

#ifndef __PTRDIFF_MAX__
# include <limits.h> /* INFRINGES ON USER NAME SPACE */
# if defined __STDC_VERSION__ && 199901 <= __STDC_VERSION__
#  include <stdint.h> /* INFRINGES ON USER NAME SPACE */
#  define YY_STDINT_H
# endif
#endif

/* Narrow types that promote to a signed type and that can represent a
   signed or unsigned integer of at least N bits.  In tables they can
   save space and decrease cache pressure.  Promoting to a signed type
   helps avoid bugs in integer arithmetic.  */

#ifdef __INT_LEAST8_MAX__
typedef __INT_LEAST8_TYPE__ yytype_int8;
#elif defined YY_STDINT_H
typedef int_least8_t yytype_int8;
#else
typedef signed char yytype_int8;
#endif

#ifdef __INT_LEAST16_MAX__
typedef __INT_LEAST16_TYPE__ yytype_int16;
#elif defined YY_STDINT_H
typedef int_least16_t yytype_int16;
#else
typedef short yytype_int16;
#endif

/* Work around bug in HP-UX 11.23, which defines these macros
   incorrectly for preprocessor constants.  This workaround can likely
   be removed in 2023, as HPE has promised support for HP-UX 11.23
   (aka HP-UX 11i v2) only through the end of 2022; see Table 2 of
   <https://h20195.www2.hpe.com/V2/getpdf.aspx/4AA4-7673ENW.pdf>.  */
#ifdef __hpux
# undef UINT_LEAST8_MAX
# undef UINT_LEAST16_MAX
# define UINT_LEAST8_MAX 255
# define UINT_LEAST16_MAX 65535
#endif

#if defined __UINT_LEAST8_MAX__ && __UINT_LEAST8_MAX__ <= __INT_MAX__
typedef __UINT_LEAST8_TYPE__ yytype_uint8;
#elif (!defined __UINT_LEAST8_MAX__ && defined YY_STDINT_H \
       && UINT_LEAST8_MAX <= INT_MAX)
typedef uint_least8_t yytype_uint8;
#elif !defined __UINT_LEAST8_MAX__ && UCHAR_MAX <= INT_MAX
typedef unsigned char yytype_uint8;
#else
typedef short yytype_uint8;
#endif

#if defined __UINT_LEAST16_MAX__ && __UINT_LEAST16_MAX__ <= __INT_MAX__
typedef __UINT_LEAST16_TYPE__ yytype_uint16;
#elif (!defined __UINT_LEAST16_MAX__ && defined YY_STDINT_H \
       && UINT_LEAST16_MAX <= INT_MAX)
typedef uint_least16_t yytype_uint16;
#elif !defined __UINT_LEAST16_MAX__ && USHRT_MAX <= INT_MAX
typedef unsigned short yytype_uint16;
#else
typedef int yytype_uint16;
#endif

#ifndef YYPTRDIFF_T
# if defined __PTRDIFF_TYPE__ && defined __PTRDIFF_MAX__
#  define YYPTRDIFF_T __PTRDIFF_TYPE__
#  define YYPTRDIFF_MAXIMUM __PTRDIFF_MAX__
# elif defined PTRDIFF_MAX
#  ifndef ptrdiff_t
#   include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  endif
#  define YYPTRDIFF_T ptrdiff_t
#  define YYPTRDIFF_MAXIMUM PTRDIFF_MAX
# else
#  define YYPTRDIFF_T long
#  define YYPTRDIFF_MAXIMUM LONG_MAX
# endif
#endif

#ifndef YYSIZE_T
# ifdef __SIZE_TYPE__
#  define YYSIZE_T __SIZE_TYPE__
# elif defined size_t
#  define YYSIZE_T size_t
# elif defined __STDC_VERSION__ && 199901 <= __STDC_VERSION__
#  include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  define YYSIZE_T size_t
# else
#  define YYSIZE_T unsigned
# endif
#endif

#define YYSIZE_MAXIMUM                                  \
  YY_CAST (YYPTRDIFF_T,                                 \
           (YYPTRDIFF_MAXIMUM < YY_CAST (YYSIZE_T, -1)  \
            ? YYPTRDIFF_MAXIMUM                         \
            : YY_CAST (YYSIZE_T, -1)))

#define YYSIZEOF(X) YY_CAST (YYPTRDIFF_T, sizeof (X))


/* Stored state numbers (used for stacks). */
typedef yytype_uint8 yy_state_t;

/* State numbers in computations.  */
typedef int yy_state_fast_t;

#ifndef YY_
# if defined YYENABLE_NLS && YYENABLE_NLS
#  if ENABLE_NLS
#   include <libintl.h> /* INFRINGES ON USER NAME SPACE */
#   define YY_(Msgid) dgettext ("bison-runtime", Msgid)
#  endif
# endif
# ifndef YY_
#  define YY_(Msgid) Msgid
# endif
#endif


#ifndef YY_ATTRIBUTE_PURE
# if defined __GNUC__ && 2 < __GNUC__ + (96 <= __GNUC_MINOR__)
#  define YY_ATTRIBUTE_PURE __attribute__ ((__pure__))
# else
#  define YY_ATTRIBUTE_PURE
# endif
#endif

#ifndef YY_ATTRIBUTE_UNUSED
# if defined __GNUC__ && 2 < __GNUC__ + (7 <= __GNUC_MINOR__)
#  define YY_ATTRIBUTE_UNUSED __attribute__ ((__unused__))
# else
#  define YY_ATTRIBUTE_UNUSED
# endif
#endif

/* Suppress unused-variable warnings by "using" E.  */
#if ! defined lint || defined __GNUC__
# define YY_USE(E) ((void) (E))
#else
# define YY_USE(E) /* empty */
#endif

/* Suppress an incorrect diagnostic about yylval being uninitialized.  */
#if defined __GNUC__ && ! defined __ICC && 406 <= __GNUC__ * 100 + __GNUC_MINOR__
# if __GNUC__ * 100 + __GNUC_MINOR__ < 407
#  define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN                           \
    _Pragma ("GCC diagnostic push")                                     \
    _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"")
# else
#  define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN                           \
    _Pragma ("GCC diagnostic push")                                     \
    _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"")              \
    _Pragma ("GCC diagnostic ignored \"-Wmaybe-uninitialized\"")
# endif
# define YY_IGNORE_MAYBE_UNINITIALIZED_END      \
    _Pragma ("GCC diagnostic pop")
#else
# define YY_INITIAL_VALUE(Value) Value
#endif
#ifndef YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_END
#endif
#ifndef YY_INITIAL_VALUE
# define YY_INITIAL_VALUE(Value) /* Nothing. */
#endif

#if defined __cplusplus && defined __GNUC__ && ! defined __ICC && 6 <= __GNUC__
# define YY_IGNORE_USELESS_CAST_BEGIN                          \
    _Pragma ("GCC diagnostic push")                            \
    _Pragma ("GCC diagnostic ignored \"-Wuseless-cast\"")
# define YY_IGNORE_USELESS_CAST_END            \
    _Pragma ("GCC diagnostic pop")
#endif
#ifndef YY_IGNORE_USELESS_CAST_BEGIN
# define YY_IGNORE_USELESS_CAST_BEGIN
# define YY_IGNORE_USELESS_CAST_END
#endif


#define YY_ASSERT(E) ((void) (0 && (E)))

#if !defined yyoverflow

/* The parser invokes alloca or malloc; define the necessary symbols.  */

# ifdef YYSTACK_USE_ALLOCA
#  if YYSTACK_USE_ALLOCA
#   ifdef __GNUC__
#    define YYSTACK_ALLOC __builtin_alloca
#   elif defined __BUILTIN_VA_ARG_INCR
#    include <alloca.h> /* INFRINGES ON USER NAME SPACE */
#   elif defined _AIX
#    define YYSTACK_ALLOC __alloca
#   elif defined _MSC_VER
#    include <malloc.h> /* INFRINGES ON USER NAME SPACE */
#    define alloca _alloca
#   else
#    define YYSTACK_ALLOC alloca
#    if ! defined _ALLOCA_H && ! defined EXIT_SUCCESS
#     include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
      /* Use EXIT_SUCCESS as a witness for stdlib.h.  */
#     ifndef EXIT_SUCCESS
#      define EXIT_SUCCESS 0
#     endif
#    endif
#   endif
#  endif
# endif

# ifdef YYSTACK_ALLOC
   /* Pacify GCC's 'empty if-body' warning.  */
#  define YYSTACK_FREE(Ptr) do { /* empty */; } while (0)
#  ifndef YYSTACK_ALLOC_MAXIMUM
    /* The OS might guarantee only one guard page at the bottom of the stack,
       and a page size can be as small as 4096 bytes.  So we cannot safely
       invoke alloca (N) if N exceeds 4096.  Use a slightly smaller number
       to allow for a few compiler-allocated temporary stack slots.  */
#   define YYSTACK_ALLOC_MAXIMUM 4032 /* reasonable circa 2006 */
#  endif
# else
#  define YYSTACK_ALLOC YYMALLOC
#  define YYSTACK_FREE YYFREE
#  ifndef YYSTACK_ALLOC_MAXIMUM
#   define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#  endif
#  if (defined __cplusplus && ! defined EXIT_SUCCESS \
       && ! ((defined YYMALLOC || defined malloc) \
             && (defined YYFREE || defined free)))
#   include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
#   ifndef EXIT_SUCCESS
#    define EXIT_SUCCESS 0
#   endif
#  endif
#  ifndef YYMALLOC
#   define YYMALLOC malloc
#   if ! defined malloc && ! defined EXIT_SUCCESS
void *malloc (YYSIZE_T); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
#  ifndef YYFREE
#   define YYFREE free
#   if ! defined free && ! defined EXIT_SUCCESS
void free (void *); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
# endif
#endif /* !defined yyoverflow */

#if (! defined yyoverflow \
     && (! defined __cplusplus \
         || (defined YYSTYPE_IS_TRIVIAL && YYSTYPE_IS_TRIVIAL)))

/* A type that is properly aligned for any stack member.  */
union yyalloc
{
  yy_state_t yyss_alloc;
  YYSTYPE yyvs_alloc;
};

/* The size of the maximum gap between one aligned stack and the next.  */
# define YYSTACK_GAP_MAXIMUM (YYSIZEOF (union yyalloc) - 1)

/* The size of an array large to enough to hold all stacks, each with
   N elements.  */
# define YYSTACK_BYTES(N) \
     ((N) * (YYSIZEOF (yy_state_t) + YYSIZEOF (YYSTYPE)) \
      + YYSTACK_GAP_MAXIMUM)

# define YYCOPY_NEEDED 1

/* Relocate STACK from its old location to the new one.  The
   local variables YYSIZE and YYSTACKSIZE give the old and new number of
   elements in the stack, and YYPTR gives the new location of the
   stack.  Advance YYPTR to a properly aligned location for the next
   stack.  */
# define YYSTACK_RELOCATE(Stack_alloc, Stack)                           \
    do                                                                  \
      {                                                                 \
        YYPTRDIFF_T yynewbytes;                                         \
        YYCOPY (&yyptr->Stack_alloc, Stack, yysize);                    \
        Stack = &yyptr->Stack_alloc;                                    \
        yynewbytes = yystacksize * YYSIZEOF (*Stack) + YYSTACK_GAP_MAXIMUM; \
        yyptr += yynewbytes / YYSIZEOF (*yyptr);                        \
      }                                                                 \
    while (0)

#endif

#if defined YYCOPY_NEEDED && YYCOPY_NEEDED
/* Copy COUNT objects from SRC to DST.  The source and destination do
   not overlap.  */
# ifndef YYCOPY
#  if defined __GNUC__ && 1 < __GNUC__
#   define YYCOPY(Dst, Src, Count) \
      __builtin_memcpy (Dst, Src, YY_CAST (YYSIZE_T, (Count)) * sizeof (*(Src)))
#  else
#   define YYCOPY(Dst, Src, Count)              \
      do                                        \
        {                                       \
          YYPTRDIFF_T yyi;                      \
          for (yyi = 0; yyi < (Count); yyi++)   \
            (Dst)[yyi] = (Src)[yyi];            \
        }                                       \
      while (0)
#  endif
# endif
#endif /* !YYCOPY_NEEDED */

/* YYFINAL -- State number of the termination state.  */
#define YYFINAL  34
/* YYLAST -- Last index in YYTABLE.  */
#define YYLAST   189

/* YYNTOKENS -- Number of terminals.  */
#define YYNTOKENS  34
/* YYNNTS -- Number of nonterminals.  */
#define YYNNTS  25
/* YYNRULES -- Number of rules.  */
#define YYNRULES  80
/* YYNSTATES -- Number of states.  */
#define YYNSTATES  147

/* YYMAXUTOK -- Last valid token kind.  */
#define YYMAXUTOK   279


/* YYTRANSLATE(TOKEN-NUM) -- Symbol number corresponding to TOKEN-NUM
   as returned by yylex, with out-of-bounds checking.  */
#define YYTRANSLATE(YYX)                                \
  (0 <= (YYX) && (YYX) <= YYMAXUTOK                     \
   ? YY_CAST (yysymbol_kind_t, yytranslate[YYX])        \
   : YYSYMBOL_YYUNDEF)

/* YYTRANSLATE[TOKEN-NUM] -- Symbol number corresponding to TOKEN-NUM
   as returned by yylex.  */
static const yytype_int8 yytranslate[] =
{
       0,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
      25,    26,     2,     2,    28,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,    27,
       2,    31,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,    32,     2,    33,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,    29,     2,    30,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     1,     2,     3,     4,
       5,     6,     7,     8,     9,    10,    11,    12,    13,    14,
      15,    16,    17,    18,    19,    20,    21,    22,    23,    24
};

#if YYDEBUG
/* YYRLINE[YYN] -- Source line where rule number YYN was defined.  */
static const yytype_int16 yyrline[] =
{
       0,    66,    66,    70,    74,    77,    83,    88,    91,    94,
      97,   100,   103,   106,   109,   112,   115,   118,   126,   129,
     135,   144,   150,   154,   158,   162,   166,   170,   176,   180,
     185,   189,   196,   201,   207,   220,   223,   226,   233,   245,
     252,   259,   263,   269,   272,   277,   286,   295,   299,   307,
     315,   321,   328,   335,   338,   344,   347,   353,   359,   365,
     371,   377,   385,   388,   394,   403,   406,   413,   419,   428,
     434,   440,   446,   449,   453,   459,   463,   469,   475,   484,
     487
};
#endif

/** Accessing symbol of state STATE.  */
#define YY_ACCESSING_SYMBOL(State) YY_CAST (yysymbol_kind_t, yystos[State])

#if YYDEBUG || 0
/* The user-facing name of the symbol whose (internal) number is
   YYSYMBOL.  No bounds checking.  */
static const char *yysymbol_name (yysymbol_kind_t yysymbol) YY_ATTRIBUTE_UNUSED;

/* YYTNAME[SYMBOL-NUM] -- String name of the symbol SYMBOL-NUM.
   First, the terminals, then, starting at YYNTOKENS, nonterminals.  */
static const char *const yytname[] =
{
  "\"end of file\"", "error", "\"invalid token\"", "T_DIGIT", "T_ID",
  "T_FUNC", "T_RETURN", "T_ADD", "T_SUB", "T_MUL", "T_DIV", "T_MOD",
  "T_VOID", "T_INT", "T_LE", "T_LT", "T_GT", "T_GE", "T_NE", "T_EQ",
  "T_AND", "T_NOT", "T_IF", "T_ELSE", "T_WHILE", "'('", "')'", "';'",
  "','", "'{'", "'}'", "'='", "'['", "']'", "$accept", "CompileUnit",
  "FuncDef", "FuncFormalParams", "FuncFormalParam", "FuncBasicParam",
  "IfStatement", "WhileStatement", "Block", "BlockItemList", "BlockItem",
  "Statement", "VarDecls", "VarDecl", "Array", "Expr", "AndExp", "CmpExp",
  "AddExp", "MulExp", "MinusExp", "UnaryExp", "PrimaryExp", "LVal",
  "RealParamList", YY_NULLPTR
};

static const char *
yysymbol_name (yysymbol_kind_t yysymbol)
{
  return yytname[yysymbol];
}
#endif

#define YYPACT_NINF (-90)

#define yypact_value_is_default(Yyn) \
  ((Yyn) == YYPACT_NINF)

#define YYTABLE_NINF (-1)

#define yytable_value_is_error(Yyn) \
  0

/* YYPACT[STATE-NUM] -- Index in YYTABLE of the portion describing
   STATE-NUM.  */
static const yytype_int16 yypact[] =
{
     106,   -90,    41,     8,    92,    38,    29,    34,    38,    92,
      76,   -90,   -90,    42,   -90,     1,    23,   141,    91,    83,
     -90,   -90,   -90,   -90,    82,    92,    37,    49,    27,   -90,
      58,    46,   -90,    65,   -90,   -90,   -90,   -90,    98,   -90,
      92,    92,    92,    92,    92,    92,    92,    92,    92,    92,
      92,    92,   -90,   -90,   -21,    94,    18,   -90,    24,    35,
      92,   126,   -90,   -90,    84,   141,    91,    91,    91,    91,
      91,    91,    83,    83,   -90,   -90,   -90,   -90,    92,   -90,
     121,    93,   100,   -90,   103,   110,   118,   111,   -90,   107,
      92,   -90,   -90,   -90,   -90,   -90,    43,   -90,   122,   120,
     -90,   -90,   123,   -90,   -90,   145,   131,   -90,   150,   148,
     156,   -90,   -90,   -90,     5,   -90,   -90,   -90,   -90,   -90,
     -90,   -90,   -90,   -90,   -90,   144,    92,    92,   140,   -90,
     -90,   157,   158,   152,    11,    11,   -90,   162,   163,   -90,
     -90,    11,    11,   -90,   -90,   -90,   -90
};

/* YYDEFACT[STATE-NUM] -- Default reduction number in state STATE-NUM.
   Performed when YYTABLE does not specify something else to do.  Zero
   means the default is an error.  */
static const yytype_int8 yydefact[] =
{
       0,    76,    78,     0,     0,     0,     0,     0,     0,     0,
       0,     2,     3,     0,    43,    40,    52,    53,    55,    62,
      65,    71,    72,    77,     0,     0,     0,    78,     0,    69,
       0,    47,    70,     0,     1,     4,     5,    42,     0,    39,
       0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
       0,     0,    73,    79,     0,     0,     0,    41,     0,     0,
       0,     0,    49,    75,    44,    54,    56,    57,    58,    59,
      60,    61,    63,    64,    66,    67,    68,    74,     0,    38,
       0,     0,     0,    18,     0,     0,     0,     0,    48,     0,
       0,    46,    80,    21,    20,    12,     0,     6,     0,     0,
      14,     8,     0,    16,    10,     0,    50,    45,     0,     0,
       0,    30,    36,    37,     0,    32,    35,    13,     7,    19,
      15,     9,    17,    11,    51,    47,     0,     0,     0,    31,
      33,     0,     0,     0,     0,     0,    34,    22,    24,    28,
      29,     0,     0,    23,    26,    27,    25
};

/* YYPGOTO[NTERM-NUM].  */
static const yytype_int16 yypgoto[] =
{
     -90,   -90,   177,   119,    89,   -90,   -90,   -90,   -82,   -90,
     -89,     0,   -90,   -90,   -61,    -3,   -90,   149,   125,   132,
      55,    50,   -90,   -90,   -90
};

/* YYDEFGOTO[NTERM-NUM].  */
static const yytype_int8 yydefgoto[] =
{
       0,    10,    11,    82,    83,    94,   112,   113,    97,   114,
     115,   116,    13,    14,    62,    15,    16,    17,    18,    19,
      20,    21,    22,    23,    54
};

/* YYTABLE[YYPACT[STATE-NUM]] -- What to do in state STATE-NUM.  If
   positive, shift that token.  If negative, reduce the rule whose
   number is the opposite.  If YYTABLE_NINF, syntax error.  */
static const yytype_uint8 yytable[] =
{
      12,    28,   101,    91,   104,    77,    33,    78,     1,     2,
      36,     4,    26,     5,     1,     2,   118,     4,   108,     5,
     121,    53,    55,   123,   108,   130,     8,   109,    39,   110,
       9,    80,     8,    30,   128,   129,     9,    80,    31,   133,
      96,     1,    27,    40,    81,   124,     1,     2,    80,     4,
      84,     5,   137,   139,    57,    29,   108,    88,    32,   143,
     145,    86,    56,     9,     8,   109,    24,   110,     9,    37,
      38,    59,    25,   111,    24,    92,    34,    60,    61,     1,
       2,     3,     4,    58,     5,     1,    27,   107,     6,     7,
       5,    63,    49,    50,    51,     1,    27,     8,    47,    48,
       5,     9,    64,     8,    74,    75,    76,     9,    52,     1,
       2,     3,     4,     8,     5,    90,    61,     9,     6,     7,
      95,    79,    96,   131,   132,    93,    98,     8,    99,    89,
     100,     9,    96,    80,   138,   140,   102,   105,    99,    99,
     106,   144,   146,     1,     2,   103,     4,    96,     5,   117,
     120,    96,    96,   108,   125,    41,    42,    43,    44,    45,
      46,     8,   109,    61,   110,     9,    66,    67,    68,    69,
      70,    71,   122,   126,    96,    60,    61,    85,    87,    72,
      73,   127,   136,   134,   135,   141,   142,    35,   119,    65
};

static const yytype_uint8 yycheck[] =
{
       0,     4,    84,    64,    86,    26,     9,    28,     3,     4,
      10,     6,     4,     8,     3,     4,    98,     6,    13,     8,
     102,    24,    25,   105,    13,   114,    21,    22,    27,    24,
      25,    13,    21,     4,    29,    30,    25,    13,     4,   128,
      29,     3,     4,    20,    26,   106,     3,     4,    13,     6,
      26,     8,   134,   135,    27,     5,    13,    60,     8,   141,
     142,    26,    25,    25,    21,    22,    25,    24,    25,    27,
      28,    25,    31,    30,    25,    78,     0,    31,    32,     3,
       4,     5,     6,    25,     8,     3,     4,    90,    12,    13,
       8,    26,     9,    10,    11,     3,     4,    21,     7,     8,
       8,    25,     4,    21,    49,    50,    51,    25,    26,     3,
       4,     5,     6,    21,     8,    31,    32,    25,    12,    13,
      27,    27,    29,   126,   127,     4,    26,    21,    28,     3,
      27,    25,    29,    13,   134,   135,    26,    26,    28,    28,
      33,   141,   142,     3,     4,    27,     6,    29,     8,    27,
      27,    29,    29,    13,     4,    14,    15,    16,    17,    18,
      19,    21,    22,    32,    24,    25,    41,    42,    43,    44,
      45,    46,    27,    25,    29,    31,    32,    58,    59,    47,
      48,    25,    30,    26,    26,    23,    23,    10,    99,    40
};

/* YYSTOS[STATE-NUM] -- The symbol kind of the accessing symbol of
   state STATE-NUM.  */
static const yytype_int8 yystos[] =
{
       0,     3,     4,     5,     6,     8,    12,    13,    21,    25,
      35,    36,    45,    46,    47,    49,    50,    51,    52,    53,
      54,    55,    56,    57,    25,    31,     4,     4,    49,    55,
       4,     4,    55,    49,     0,    36,    45,    27,    28,    27,
      20,    14,    15,    16,    17,    18,    19,     7,     8,     9,
      10,    11,    26,    49,    58,    49,    25,    27,    25,    25,
      31,    32,    48,    26,     4,    51,    52,    52,    52,    52,
      52,    52,    53,    53,    54,    54,    54,    26,    28,    27,
      13,    26,    37,    38,    26,    37,    26,    37,    49,     3,
      31,    48,    49,     4,    39,    27,    29,    42,    26,    28,
      27,    42,    26,    27,    42,    26,    33,    49,    13,    22,
      24,    30,    40,    41,    43,    44,    45,    27,    42,    38,
      27,    42,    27,    42,    48,     4,    25,    25,    29,    30,
      44,    49,    49,    44,    26,    26,    30,    42,    45,    42,
      45,    23,    23,    42,    45,    42,    45
};

/* YYR1[RULE-NUM] -- Symbol kind of the left-hand side of rule RULE-NUM.  */
static const yytype_int8 yyr1[] =
{
       0,    34,    35,    35,    35,    35,    36,    36,    36,    36,
      36,    36,    36,    36,    36,    36,    36,    36,    37,    37,
      38,    39,    40,    40,    40,    40,    40,    40,    41,    41,
      42,    42,    43,    43,    43,    44,    44,    44,    45,    45,
      45,    45,    45,    46,    46,    46,    46,    47,    47,    47,
      48,    48,    49,    50,    50,    51,    51,    51,    51,    51,
      51,    51,    52,    52,    52,    53,    53,    53,    53,    54,
      54,    54,    55,    55,    55,    56,    56,    56,    57,    58,
      58
};

/* YYR2[RULE-NUM] -- Number of symbols on the right-hand side of rule RULE-NUM.  */
static const yytype_int8 yyr2[] =
{
       0,     2,     1,     1,     2,     2,     5,     6,     5,     6,
       5,     6,     5,     6,     5,     6,     5,     6,     1,     3,
       2,     1,     5,     7,     5,     7,     7,     7,     5,     5,
       2,     3,     1,     2,     4,     1,     1,     1,     4,     2,
       1,     3,     2,     1,     3,     5,     4,     2,     4,     3,
       3,     4,     1,     1,     3,     1,     3,     3,     3,     3,
       3,     3,     1,     3,     3,     1,     3,     3,     3,     2,
       2,     1,     1,     3,     4,     3,     1,     1,     1,     1,
       3
};


enum { YYENOMEM = -2 };

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (yychar = YYEMPTY)

#define YYACCEPT        goto yyacceptlab
#define YYABORT         goto yyabortlab
#define YYERROR         goto yyerrorlab
#define YYNOMEM         goto yyexhaustedlab


#define YYRECOVERING()  (!!yyerrstatus)

#define YYBACKUP(Token, Value)                                    \
  do                                                              \
    if (yychar == YYEMPTY)                                        \
      {                                                           \
        yychar = (Token);                                         \
        yylval = (Value);                                         \
        YYPOPSTACK (yylen);                                       \
        yystate = *yyssp;                                         \
        goto yybackup;                                            \
      }                                                           \
    else                                                          \
      {                                                           \
        yyerror (YY_("syntax error: cannot back up")); \
        YYERROR;                                                  \
      }                                                           \
  while (0)

/* Backward compatibility with an undocumented macro.
   Use YYerror or YYUNDEF. */
#define YYERRCODE YYUNDEF


/* Enable debugging if requested.  */
#if YYDEBUG

# ifndef YYFPRINTF
#  include <stdio.h> /* INFRINGES ON USER NAME SPACE */
#  define YYFPRINTF fprintf
# endif

# define YYDPRINTF(Args)                        \
do {                                            \
  if (yydebug)                                  \
    YYFPRINTF Args;                             \
} while (0)




# define YY_SYMBOL_PRINT(Title, Kind, Value, Location)                    \
do {                                                                      \
  if (yydebug)                                                            \
    {                                                                     \
      YYFPRINTF (stderr, "%s ", Title);                                   \
      yy_symbol_print (stderr,                                            \
                  Kind, Value); \
      YYFPRINTF (stderr, "\n");                                           \
    }                                                                     \
} while (0)


/*-----------------------------------.
| Print this symbol's value on YYO.  |
`-----------------------------------*/

static void
yy_symbol_value_print (FILE *yyo,
                       yysymbol_kind_t yykind, YYSTYPE const * const yyvaluep)
{
  FILE *yyoutput = yyo;
  YY_USE (yyoutput);
  if (!yyvaluep)
    return;
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  YY_USE (yykind);
  YY_IGNORE_MAYBE_UNINITIALIZED_END
}


/*---------------------------.
| Print this symbol on YYO.  |
`---------------------------*/

static void
yy_symbol_print (FILE *yyo,
                 yysymbol_kind_t yykind, YYSTYPE const * const yyvaluep)
{
  YYFPRINTF (yyo, "%s %s (",
             yykind < YYNTOKENS ? "token" : "nterm", yysymbol_name (yykind));

  yy_symbol_value_print (yyo, yykind, yyvaluep);
  YYFPRINTF (yyo, ")");
}

/*------------------------------------------------------------------.
| yy_stack_print -- Print the state stack from its BOTTOM up to its |
| TOP (included).                                                   |
`------------------------------------------------------------------*/

static void
yy_stack_print (yy_state_t *yybottom, yy_state_t *yytop)
{
  YYFPRINTF (stderr, "Stack now");
  for (; yybottom <= yytop; yybottom++)
    {
      int yybot = *yybottom;
      YYFPRINTF (stderr, " %d", yybot);
    }
  YYFPRINTF (stderr, "\n");
}

# define YY_STACK_PRINT(Bottom, Top)                            \
do {                                                            \
  if (yydebug)                                                  \
    yy_stack_print ((Bottom), (Top));                           \
} while (0)


/*------------------------------------------------.
| Report that the YYRULE is going to be reduced.  |
`------------------------------------------------*/

static void
yy_reduce_print (yy_state_t *yyssp, YYSTYPE *yyvsp,
                 int yyrule)
{
  int yylno = yyrline[yyrule];
  int yynrhs = yyr2[yyrule];
  int yyi;
  YYFPRINTF (stderr, "Reducing stack by rule %d (line %d):\n",
             yyrule - 1, yylno);
  /* The symbols being reduced.  */
  for (yyi = 0; yyi < yynrhs; yyi++)
    {
      YYFPRINTF (stderr, "   $%d = ", yyi + 1);
      yy_symbol_print (stderr,
                       YY_ACCESSING_SYMBOL (+yyssp[yyi + 1 - yynrhs]),
                       &yyvsp[(yyi + 1) - (yynrhs)]);
      YYFPRINTF (stderr, "\n");
    }
}

# define YY_REDUCE_PRINT(Rule)          \
do {                                    \
  if (yydebug)                          \
    yy_reduce_print (yyssp, yyvsp, Rule); \
} while (0)

/* Nonzero means print parse trace.  It is left uninitialized so that
   multiple parsers can coexist.  */
int yydebug;
#else /* !YYDEBUG */
# define YYDPRINTF(Args) ((void) 0)
# define YY_SYMBOL_PRINT(Title, Kind, Value, Location)
# define YY_STACK_PRINT(Bottom, Top)
# define YY_REDUCE_PRINT(Rule)
#endif /* !YYDEBUG */


/* YYINITDEPTH -- initial size of the parser's stacks.  */
#ifndef YYINITDEPTH
# define YYINITDEPTH 200
#endif

/* YYMAXDEPTH -- maximum size the stacks can grow to (effective only
   if the built-in stack extension method is used).

   Do not make this value too large; the results are undefined if
   YYSTACK_ALLOC_MAXIMUM < YYSTACK_BYTES (YYMAXDEPTH)
   evaluated with infinite-precision integer arithmetic.  */

#ifndef YYMAXDEPTH
# define YYMAXDEPTH 10000
#endif






/*-----------------------------------------------.
| Release the memory associated to this symbol.  |
`-----------------------------------------------*/

static void
yydestruct (const char *yymsg,
            yysymbol_kind_t yykind, YYSTYPE *yyvaluep)
{
  YY_USE (yyvaluep);
  if (!yymsg)
    yymsg = "Deleting";
  YY_SYMBOL_PRINT (yymsg, yykind, yyvaluep, yylocationp);

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  YY_USE (yykind);
  YY_IGNORE_MAYBE_UNINITIALIZED_END
}


/* Lookahead token kind.  */
int yychar;

/* The semantic value of the lookahead symbol.  */
YYSTYPE yylval;
/* Number of syntax errors so far.  */
int yynerrs;




/*----------.
| yyparse.  |
`----------*/

int
yyparse (void)
{
    yy_state_fast_t yystate = 0;
    /* Number of tokens to shift before error messages enabled.  */
    int yyerrstatus = 0;

    /* Refer to the stacks through separate pointers, to allow yyoverflow
       to reallocate them elsewhere.  */

    /* Their size.  */
    YYPTRDIFF_T yystacksize = YYINITDEPTH;

    /* The state stack: array, bottom, top.  */
    yy_state_t yyssa[YYINITDEPTH];
    yy_state_t *yyss = yyssa;
    yy_state_t *yyssp = yyss;

    /* The semantic value stack: array, bottom, top.  */
    YYSTYPE yyvsa[YYINITDEPTH];
    YYSTYPE *yyvs = yyvsa;
    YYSTYPE *yyvsp = yyvs;

  int yyn;
  /* The return value of yyparse.  */
  int yyresult;
  /* Lookahead symbol kind.  */
  yysymbol_kind_t yytoken = YYSYMBOL_YYEMPTY;
  /* The variables used to return semantic value and location from the
     action routines.  */
  YYSTYPE yyval;



#define YYPOPSTACK(N)   (yyvsp -= (N), yyssp -= (N))

  /* The number of symbols on the RHS of the reduced rule.
     Keep to zero when no symbol should be popped.  */
  int yylen = 0;

  YYDPRINTF ((stderr, "Starting parse\n"));

  yychar = YYEMPTY; /* Cause a token to be read.  */

  goto yysetstate;


/*------------------------------------------------------------.
| yynewstate -- push a new state, which is found in yystate.  |
`------------------------------------------------------------*/
yynewstate:
  /* In all cases, when you get here, the value and location stacks
     have just been pushed.  So pushing a state here evens the stacks.  */
  yyssp++;


/*--------------------------------------------------------------------.
| yysetstate -- set current state (the top of the stack) to yystate.  |
`--------------------------------------------------------------------*/
yysetstate:
  YYDPRINTF ((stderr, "Entering state %d\n", yystate));
  YY_ASSERT (0 <= yystate && yystate < YYNSTATES);
  YY_IGNORE_USELESS_CAST_BEGIN
  *yyssp = YY_CAST (yy_state_t, yystate);
  YY_IGNORE_USELESS_CAST_END
  YY_STACK_PRINT (yyss, yyssp);

  if (yyss + yystacksize - 1 <= yyssp)
#if !defined yyoverflow && !defined YYSTACK_RELOCATE
    YYNOMEM;
#else
    {
      /* Get the current used size of the three stacks, in elements.  */
      YYPTRDIFF_T yysize = yyssp - yyss + 1;

# if defined yyoverflow
      {
        /* Give user a chance to reallocate the stack.  Use copies of
           these so that the &'s don't force the real ones into
           memory.  */
        yy_state_t *yyss1 = yyss;
        YYSTYPE *yyvs1 = yyvs;

        /* Each stack pointer address is followed by the size of the
           data in use in that stack, in bytes.  This used to be a
           conditional around just the two extra args, but that might
           be undefined if yyoverflow is a macro.  */
        yyoverflow (YY_("memory exhausted"),
                    &yyss1, yysize * YYSIZEOF (*yyssp),
                    &yyvs1, yysize * YYSIZEOF (*yyvsp),
                    &yystacksize);
        yyss = yyss1;
        yyvs = yyvs1;
      }
# else /* defined YYSTACK_RELOCATE */
      /* Extend the stack our own way.  */
      if (YYMAXDEPTH <= yystacksize)
        YYNOMEM;
      yystacksize *= 2;
      if (YYMAXDEPTH < yystacksize)
        yystacksize = YYMAXDEPTH;

      {
        yy_state_t *yyss1 = yyss;
        union yyalloc *yyptr =
          YY_CAST (union yyalloc *,
                   YYSTACK_ALLOC (YY_CAST (YYSIZE_T, YYSTACK_BYTES (yystacksize))));
        if (! yyptr)
          YYNOMEM;
        YYSTACK_RELOCATE (yyss_alloc, yyss);
        YYSTACK_RELOCATE (yyvs_alloc, yyvs);
#  undef YYSTACK_RELOCATE
        if (yyss1 != yyssa)
          YYSTACK_FREE (yyss1);
      }
# endif

      yyssp = yyss + yysize - 1;
      yyvsp = yyvs + yysize - 1;

      YY_IGNORE_USELESS_CAST_BEGIN
      YYDPRINTF ((stderr, "Stack size increased to %ld\n",
                  YY_CAST (long, yystacksize)));
      YY_IGNORE_USELESS_CAST_END

      if (yyss + yystacksize - 1 <= yyssp)
        YYABORT;
    }
#endif /* !defined yyoverflow && !defined YYSTACK_RELOCATE */


  if (yystate == YYFINAL)
    YYACCEPT;

  goto yybackup;


/*-----------.
| yybackup.  |
`-----------*/
yybackup:
  /* Do appropriate processing given the current state.  Read a
     lookahead token if we need one and don't already have one.  */

  /* First try to decide what to do without reference to lookahead token.  */
  yyn = yypact[yystate];
  if (yypact_value_is_default (yyn))
    goto yydefault;

  /* Not known => get a lookahead token if don't already have one.  */

  /* YYCHAR is either empty, or end-of-input, or a valid lookahead.  */
  if (yychar == YYEMPTY)
    {
      YYDPRINTF ((stderr, "Reading a token\n"));
      yychar = yylex ();
    }

  if (yychar <= YYEOF)
    {
      yychar = YYEOF;
      yytoken = YYSYMBOL_YYEOF;
      YYDPRINTF ((stderr, "Now at end of input.\n"));
    }
  else if (yychar == YYerror)
    {
      /* The scanner already issued an error message, process directly
         to error recovery.  But do not keep the error token as
         lookahead, it is too special and may lead us to an endless
         loop in error recovery. */
      yychar = YYUNDEF;
      yytoken = YYSYMBOL_YYerror;
      goto yyerrlab1;
    }
  else
    {
      yytoken = YYTRANSLATE (yychar);
      YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc);
    }

  /* If the proper action on seeing token YYTOKEN is to reduce or to
     detect an error, take that action.  */
  yyn += yytoken;
  if (yyn < 0 || YYLAST < yyn || yycheck[yyn] != yytoken)
    goto yydefault;
  yyn = yytable[yyn];
  if (yyn <= 0)
    {
      if (yytable_value_is_error (yyn))
        goto yyerrlab;
      yyn = -yyn;
      goto yyreduce;
    }

  /* Count tokens shifted since error; after three, turn off error
     status.  */
  if (yyerrstatus)
    yyerrstatus--;

  /* Shift the lookahead token.  */
  YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc);
  yystate = yyn;
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END

  /* Discard the shifted token.  */
  yychar = YYEMPTY;
  goto yynewstate;


/*-----------------------------------------------------------.
| yydefault -- do the default action for the current state.  |
`-----------------------------------------------------------*/
yydefault:
  yyn = yydefact[yystate];
  if (yyn == 0)
    goto yyerrlab;
  goto yyreduce;


/*-----------------------------.
| yyreduce -- do a reduction.  |
`-----------------------------*/
yyreduce:
  /* yyn is the number of a rule to reduce with.  */
  yylen = yyr2[yyn];

  /* If YYLEN is nonzero, implement the default value of the action:
     '$$ = $1'.

     Otherwise, the following line sets YYVAL to garbage.
     This behavior is undocumented and Bison
     users should not rely upon it.  Assigning to YYVAL
     unconditionally makes the parser a bit smaller, and it avoids a
     GCC warning that YYVAL may be used uninitialized.  */
  yyval = yyvsp[1-yylen];


  YY_REDUCE_PRINT (yyn);
  switch (yyn)
    {
  case 2: /* CompileUnit: FuncDef  */
#line 66 "/root/calculator/frontend/flexbison/Calculator.y"
                      {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_COMPILE_UNIT, (yyvsp[0].node));
        ast_root = (yyval.node);
    }
#line 1239 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 3: /* CompileUnit: Statement  */
#line 70 "/root/calculator/frontend/flexbison/Calculator.y"
                {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_COMPILE_UNIT, (yyvsp[0].node));
        ast_root = (yyval.node);
    }
#line 1248 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 4: /* CompileUnit: CompileUnit FuncDef  */
#line 74 "/root/calculator/frontend/flexbison/Calculator.y"
                          {
        (yyval.node) = insert_ast_node((yyvsp[-1].node), (yyvsp[0].node));
    }
#line 1256 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 5: /* CompileUnit: CompileUnit Statement  */
#line 77 "/root/calculator/frontend/flexbison/Calculator.y"
                            {
        (yyval.node) = insert_ast_node((yyvsp[-1].node), (yyvsp[0].node));
    }
#line 1264 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 6: /* FuncDef: T_FUNC T_ID '(' ')' Block  */
#line 83 "/root/calculator/frontend/flexbison/Calculator.y"
                                     {
		// 这里由于函数返回值类型和变量定义类型的识别会有冲突，所以不能把类型单独处理

        (yyval.node) = create_func_def((yyvsp[-3].var_id).lineno, (yyvsp[-3].var_id).id, (yyvsp[0].node), nullptr);
    }
#line 1274 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 7: /* FuncDef: T_FUNC T_ID '(' FuncFormalParams ')' Block  */
#line 88 "/root/calculator/frontend/flexbison/Calculator.y"
                                                 {
        (yyval.node) = create_func_def((yyvsp[-4].var_id).lineno, (yyvsp[-4].var_id).id, (yyvsp[0].node), (yyvsp[-2].node));
    }
#line 1282 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 8: /* FuncDef: T_VOID T_ID '(' ')' Block  */
#line 91 "/root/calculator/frontend/flexbison/Calculator.y"
                                     {
        (yyval.node) = create_func_def((yyvsp[-3].var_id).lineno, (yyvsp[-3].var_id).id, (yyvsp[0].node), nullptr);
    }
#line 1290 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 9: /* FuncDef: T_VOID T_ID '(' FuncFormalParams ')' Block  */
#line 94 "/root/calculator/frontend/flexbison/Calculator.y"
                                                     {
        (yyval.node) = create_func_def((yyvsp[-4].var_id).lineno, (yyvsp[-4].var_id).id, (yyvsp[0].node), (yyvsp[-2].node));
    }
#line 1298 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 10: /* FuncDef: T_INT T_ID '(' ')' Block  */
#line 97 "/root/calculator/frontend/flexbison/Calculator.y"
                                    {
        (yyval.node) = create_func_def((yyvsp[-3].var_id).lineno, (yyvsp[-3].var_id).id, (yyvsp[0].node), nullptr);
    }
#line 1306 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 11: /* FuncDef: T_INT T_ID '(' FuncFormalParams ')' Block  */
#line 100 "/root/calculator/frontend/flexbison/Calculator.y"
                                                    {
        (yyval.node) = create_func_def((yyvsp[-4].var_id).lineno, (yyvsp[-4].var_id).id, (yyvsp[0].node), (yyvsp[-2].node));
    }
#line 1314 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 12: /* FuncDef: T_FUNC T_ID '(' ')' ';'  */
#line 103 "/root/calculator/frontend/flexbison/Calculator.y"
                                  {
        (yyval.node) = create_func_def((yyvsp[-3].var_id).lineno, (yyvsp[-3].var_id).id, nullptr);
    }
#line 1322 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 13: /* FuncDef: T_FUNC T_ID '(' FuncFormalParams ')' ';'  */
#line 106 "/root/calculator/frontend/flexbison/Calculator.y"
                                                   {
        (yyval.node) = create_func_def((yyvsp[-4].var_id).lineno, (yyvsp[-4].var_id).id, (yyvsp[-2].node));
    }
#line 1330 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 14: /* FuncDef: T_VOID T_ID '(' ')' ';'  */
#line 109 "/root/calculator/frontend/flexbison/Calculator.y"
                                   {
        (yyval.node) = create_func_def((yyvsp[-3].var_id).lineno, (yyvsp[-3].var_id).id, nullptr);
    }
#line 1338 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 15: /* FuncDef: T_VOID T_ID '(' FuncFormalParams ')' ';'  */
#line 112 "/root/calculator/frontend/flexbison/Calculator.y"
                                                   {
        (yyval.node) = create_func_def((yyvsp[-4].var_id).lineno, (yyvsp[-4].var_id).id, (yyvsp[-2].node));
    }
#line 1346 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 16: /* FuncDef: T_INT T_ID '(' ')' ';'  */
#line 115 "/root/calculator/frontend/flexbison/Calculator.y"
                                  {
        (yyval.node) = create_func_def((yyvsp[-3].var_id).lineno, (yyvsp[-3].var_id).id, nullptr);
    }
#line 1354 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 17: /* FuncDef: T_INT T_ID '(' FuncFormalParams ')' ';'  */
#line 118 "/root/calculator/frontend/flexbison/Calculator.y"
                                                  {
        (yyval.node) = create_func_def((yyvsp[-4].var_id).lineno, (yyvsp[-4].var_id).id, (yyvsp[-2].node));
    }
#line 1362 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 18: /* FuncFormalParams: FuncFormalParam  */
#line 126 "/root/calculator/frontend/flexbison/Calculator.y"
                                    {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_FUNC_FORMAL_PARAMS, (yyvsp[0].node));
    }
#line 1370 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 19: /* FuncFormalParams: FuncFormalParams ',' FuncFormalParam  */
#line 129 "/root/calculator/frontend/flexbison/Calculator.y"
                                           {
        (yyval.node) = insert_ast_node((yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1378 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 20: /* FuncFormalParam: T_INT FuncBasicParam  */
#line 135 "/root/calculator/frontend/flexbison/Calculator.y"
                                        {
		// 目前只支持int类型的变量，所以这里直接识别int

		//创建int类型的节点
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_TYPE_INT, (yyvsp[0].node), nullptr);
    }
#line 1389 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 21: /* FuncBasicParam: T_ID  */
#line 144 "/root/calculator/frontend/flexbison/Calculator.y"
                      {
        (yyval.node) = create_func_formal_param((yyvsp[0].var_id).lineno, (yyvsp[0].var_id).id);
    }
#line 1397 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 22: /* IfStatement: T_IF '(' Expr ')' Block  */
#line 150 "/root/calculator/frontend/flexbison/Calculator.y"
                                     {
		//创建if语句的节点
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_IF, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 1406 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 23: /* IfStatement: T_IF '(' Expr ')' Block T_ELSE Block  */
#line 154 "/root/calculator/frontend/flexbison/Calculator.y"
                                              {
		//创建if语句的节点
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_IF, (yyvsp[-4].node), (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 1415 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 24: /* IfStatement: T_IF '(' Expr ')' Statement  */
#line 158 "/root/calculator/frontend/flexbison/Calculator.y"
                                     {
		//创建if语句的节点
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_IF, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 1424 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 25: /* IfStatement: T_IF '(' Expr ')' Statement T_ELSE Statement  */
#line 162 "/root/calculator/frontend/flexbison/Calculator.y"
                                                      {
		//创建if语句的节点
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_IF, (yyvsp[-4].node), (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 1433 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 26: /* IfStatement: T_IF '(' Expr ')' Block T_ELSE Statement  */
#line 166 "/root/calculator/frontend/flexbison/Calculator.y"
                                                  {
		//创建if语句的节点
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_IF, (yyvsp[-4].node), (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 1442 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 27: /* IfStatement: T_IF '(' Expr ')' Statement T_ELSE Block  */
#line 170 "/root/calculator/frontend/flexbison/Calculator.y"
                                                  {
		//创建if语句的节点
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_IF, (yyvsp[-4].node), (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 1451 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 28: /* WhileStatement: T_WHILE '(' Expr ')' Block  */
#line 176 "/root/calculator/frontend/flexbison/Calculator.y"
                                           {
		//创建while语句节点
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_WHILE, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 1460 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 29: /* WhileStatement: T_WHILE '(' Expr ')' Statement  */
#line 180 "/root/calculator/frontend/flexbison/Calculator.y"
                                        {
		//创建while语句节点
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_WHILE, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 1469 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 30: /* Block: '{' '}'  */
#line 185 "/root/calculator/frontend/flexbison/Calculator.y"
                {
        // 语句块没有语句
        (yyval.node) = nullptr;
    }
#line 1478 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 31: /* Block: '{' BlockItemList '}'  */
#line 189 "/root/calculator/frontend/flexbison/Calculator.y"
                            {
        // 语句块含有语句
        (yyval.node) = (yyvsp[-1].node);
    }
#line 1487 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 32: /* BlockItemList: BlockItem  */
#line 196 "/root/calculator/frontend/flexbison/Calculator.y"
                          {
        // 第一个左侧的孩子节点归约成Block父节点，后续语句可不断作为孩子追加到block中
        // 创建一个AST_OP_BLOCK类型的中间节点，孩子为Statement($1)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_BLOCK, (yyvsp[0].node), nullptr);
    }
#line 1497 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 33: /* BlockItemList: BlockItemList BlockItem  */
#line 201 "/root/calculator/frontend/flexbison/Calculator.y"
                               {
        // 采用左递归的文法产生式，可以使得Block节点在上个产生式创建，后续递归追加孩子节点
        // 请注意，不要采用右递归，左递归翻遍孩子的追加
        // BlockItem($2)作为Block($1)的孩子 
        (yyval.node) = insert_ast_node((yyvsp[-1].node), (yyvsp[0].node));
    }
#line 1508 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 34: /* BlockItemList: BlockItemList '{' BlockItem '}'  */
#line 207 "/root/calculator/frontend/flexbison/Calculator.y"
                                      {
        // 采用左递归的文法产生式，可以使得Block节点在上个产生式创建，后续递归追加孩子节点
        // 请注意，不要采用右递归，左递归翻遍孩子的追加
        // BlockItem($2)作为Block($1)的孩子 
		
		// 嵌套的大括号，作用域不同
		ast_node * block_node = new_ast_node(ast_operator_type::AST_OP_BLOCK, (yyvsp[-1].node), nullptr);
        (yyval.node) = insert_ast_node((yyvsp[-3].node), block_node);
    }
#line 1522 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 35: /* BlockItem: Statement  */
#line 220 "/root/calculator/frontend/flexbison/Calculator.y"
                       {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1530 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 36: /* BlockItem: IfStatement  */
#line 223 "/root/calculator/frontend/flexbison/Calculator.y"
                      {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1538 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 37: /* BlockItem: WhileStatement  */
#line 226 "/root/calculator/frontend/flexbison/Calculator.y"
                         {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1546 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 38: /* Statement: T_ID '=' Expr ';'  */
#line 233 "/root/calculator/frontend/flexbison/Calculator.y"
                              {
        // 归约到Statement时要执行的语义动作程序
        // 赋值语句，不显示值

		// 变量节点
		ast_node * id_node = new_ast_leaf_node(var_id_attr{(yyvsp[-3].var_id).id, (yyvsp[-3].var_id).lineno});

		free((yyvsp[-3].var_id).id);

        // 创建一个AST_OP_ASSIGN类型的中间节点，孩子为Id和Expr($3)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_ASSIGN, id_node, (yyvsp[-1].node), nullptr);
    }
#line 1563 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 39: /* Statement: Expr ';'  */
#line 245 "/root/calculator/frontend/flexbison/Calculator.y"
               {
        // Expr归约到Statement时要执行的语义动作程序
        // 表达式语句，不显示表达式的值

        // 创建一个AST_OP_EXPR类型的中间节点，孩子为Expr($1)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_EXPR, (yyvsp[-1].node), nullptr);
    }
#line 1575 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 40: /* Statement: Expr  */
#line 252 "/root/calculator/frontend/flexbison/Calculator.y"
           {
        // Expr归约到Statement时要执行的语义动作程序
        // 表达式语句，需要显示表达式的值

        // 创建一个AST_OP_EXPR_SHOW类型的中间节点，孩子为Expr($1)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_EXPR_SHOW, (yyvsp[0].node), nullptr);
    }
#line 1587 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 41: /* Statement: T_RETURN Expr ';'  */
#line 259 "/root/calculator/frontend/flexbison/Calculator.y"
                        {
        // 返回语句
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_RETURN_STATEMENT, (yyvsp[-1].node), nullptr);
    }
#line 1596 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 42: /* Statement: VarDecls ';'  */
#line 263 "/root/calculator/frontend/flexbison/Calculator.y"
                      {
		(yyval.node) = (yyvsp[-1].node);
	}
#line 1604 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 43: /* VarDecls: VarDecl  */
#line 269 "/root/calculator/frontend/flexbison/Calculator.y"
                   {
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_VAR_DECLS, (yyvsp[0].node));
	}
#line 1612 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 44: /* VarDecls: VarDecls ',' T_ID  */
#line 272 "/root/calculator/frontend/flexbison/Calculator.y"
                            {
		ast_node * type_node = new_ast_node(ast_operator_type::AST_OP_TYPE_INT, nullptr);
        ast_node * var_node = create_var_decl((yyvsp[0].var_id).lineno, (yyvsp[0].var_id).id, type_node);
		(yyval.node) = insert_ast_node((yyvsp[-2].node), var_node);
	}
#line 1622 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 45: /* VarDecls: VarDecls ',' T_ID '=' Expr  */
#line 277 "/root/calculator/frontend/flexbison/Calculator.y"
                                     {
		ast_node * type_node = new_ast_node(ast_operator_type::AST_OP_TYPE_INT, nullptr);
		ast_node * id_node = new_ast_leaf_node(var_id_attr{(yyvsp[-2].var_id).id, (yyvsp[-2].var_id).lineno});

        // 创建一个AST_OP_ASSIGN类型的中间节点，孩子为Id和Expr($4)
        ast_node * assign_node = new_ast_node(ast_operator_type::AST_OP_ASSIGN, id_node, (yyvsp[0].node), nullptr);
		ast_node * var_node = create_var_decl((yyvsp[-2].var_id).lineno, (yyvsp[-2].var_id).id, type_node, assign_node);
		(yyval.node) = insert_ast_node((yyvsp[-4].node), var_node);
	}
#line 1636 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 46: /* VarDecls: VarDecls ',' T_ID Array  */
#line 286 "/root/calculator/frontend/flexbison/Calculator.y"
                                  {
		// 创建一个数组节点

		ast_node * id_node = new_ast_leaf_node(var_id_attr{(yyvsp[-1].var_id).id, (yyvsp[-1].var_id).lineno});
		ast_node * array = new_ast_node(ast_operator_type::AST_OP_VAR_DECL, id_node, (yyvsp[0].node), nullptr);
		(yyval.node) = insert_ast_node((yyvsp[-3].node), array);
	}
#line 1648 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 47: /* VarDecl: T_INT T_ID  */
#line 295 "/root/calculator/frontend/flexbison/Calculator.y"
                     {
		ast_node * type_node = new_ast_node(ast_operator_type::AST_OP_TYPE_INT, nullptr);
        (yyval.node) = create_var_decl((yyvsp[0].var_id).lineno, (yyvsp[0].var_id).id, type_node);
    }
#line 1657 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 48: /* VarDecl: T_INT T_ID '=' Expr  */
#line 299 "/root/calculator/frontend/flexbison/Calculator.y"
                              {
		ast_node * type_node = new_ast_node(ast_operator_type::AST_OP_TYPE_INT, nullptr);
		ast_node * id_node = new_ast_leaf_node(var_id_attr{(yyvsp[-2].var_id).id, (yyvsp[-2].var_id).lineno});

        // 创建一个AST_OP_ASSIGN类型的中间节点，孩子为Id和Expr($4)
        ast_node * assign_node = new_ast_node(ast_operator_type::AST_OP_ASSIGN, id_node, (yyvsp[0].node), nullptr);
		(yyval.node) = create_var_decl((yyvsp[-2].var_id).lineno, (yyvsp[-2].var_id).id, type_node, assign_node);
	}
#line 1670 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 49: /* VarDecl: T_INT T_ID Array  */
#line 307 "/root/calculator/frontend/flexbison/Calculator.y"
                          {
        // 创建数组节点
		ast_node * id_node = new_ast_leaf_node(var_id_attr{(yyvsp[-1].var_id).id, (yyvsp[-1].var_id).lineno});
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_VAR_DECL, (yyvsp[0].node), id_node, nullptr);
    }
#line 1680 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 50: /* Array: '[' T_DIGIT ']'  */
#line 315 "/root/calculator/frontend/flexbison/Calculator.y"
                        {
        // 创建数组节点
		ast_node * type_node = new_ast_node(ast_operator_type::AST_OP_TYPE_INT, nullptr);
		ast_node * digit_node = new_ast_leaf_node(digit_int_attr{(yyvsp[-1].integer_num).val, (yyvsp[-1].integer_num).lineno});
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_ARRAY_DECL, digit_node, type_node, nullptr);
    }
#line 1691 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 51: /* Array: '[' T_DIGIT ']' Array  */
#line 321 "/root/calculator/frontend/flexbison/Calculator.y"
                            {
		// 多维数组
		ast_node * digit_node = new_ast_leaf_node(digit_int_attr{(yyvsp[-2].integer_num).val, (yyvsp[-2].integer_num).lineno});
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_ARRAY_DECL, digit_node, (yyvsp[0].node), nullptr);
    }
#line 1701 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 52: /* Expr: AndExp  */
#line 328 "/root/calculator/frontend/flexbison/Calculator.y"
              {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1709 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 53: /* AndExp: CmpExp  */
#line 335 "/root/calculator/frontend/flexbison/Calculator.y"
                {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1717 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 54: /* AndExp: AndExp T_AND CmpExp  */
#line 338 "/root/calculator/frontend/flexbison/Calculator.y"
                              {
		// 创建一个AST_OP_AND类型的中间节点，孩子为AndExp和CmpExp
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_AND, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
    }
#line 1726 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 55: /* CmpExp: AddExp  */
#line 344 "/root/calculator/frontend/flexbison/Calculator.y"
                {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1734 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 56: /* CmpExp: CmpExp T_LE AddExp  */
#line 347 "/root/calculator/frontend/flexbison/Calculator.y"
                             {
        /* Expr = Expr <= MulExp */

        // 创建一个AST_OP_T_LE类型的中间节点，孩子为Expr($1)和MulExp($3)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_LE, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
    }
#line 1745 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 57: /* CmpExp: CmpExp T_LT AddExp  */
#line 353 "/root/calculator/frontend/flexbison/Calculator.y"
                             {
        /* Expr = Expr < MulExp */

        // 创建一个AST_OP_LT类型的中间节点，孩子为Expr($1)和MulExp($3)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_LT, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
    }
#line 1756 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 58: /* CmpExp: CmpExp T_GT AddExp  */
#line 359 "/root/calculator/frontend/flexbison/Calculator.y"
                             {
        /* Expr = Expr > MulExp */

        // 创建一个AST_OP_GT类型的中间节点，孩子为Expr($1)和MulExp($3)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_GT, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
    }
#line 1767 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 59: /* CmpExp: CmpExp T_GE AddExp  */
#line 365 "/root/calculator/frontend/flexbison/Calculator.y"
                             {
        /* Expr = Expr >= MulExp */

        // 创建一个AST_OP_GE类型的中间节点，孩子为Expr($1)和MulExp($3)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_GE, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
    }
#line 1778 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 60: /* CmpExp: CmpExp T_NE AddExp  */
#line 371 "/root/calculator/frontend/flexbison/Calculator.y"
                             {
        /* Expr = Expr != MulExp */

        // 创建一个AST_OP_NE类型的中间节点，孩子为Expr($1)和MulExp($3)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_NE, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
    }
#line 1789 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 61: /* CmpExp: CmpExp T_EQ AddExp  */
#line 377 "/root/calculator/frontend/flexbison/Calculator.y"
                             {
        /* Expr = Expr = MulExp */

        // 创建一个AST_OP_EQ类型的中间节点，孩子为Expr($1)和MulExp($3)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_EQ, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
    }
#line 1800 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 62: /* AddExp: MulExp  */
#line 385 "/root/calculator/frontend/flexbison/Calculator.y"
                {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1808 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 63: /* AddExp: AddExp T_ADD MulExp  */
#line 388 "/root/calculator/frontend/flexbison/Calculator.y"
                              {
        /* Expr = Expr + Term */

        // 创建一个AST_OP_ADD类型的中间节点，孩子为Expr($1)和Term($3)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_ADD, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
    }
#line 1819 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 64: /* AddExp: AddExp T_SUB MulExp  */
#line 394 "/root/calculator/frontend/flexbison/Calculator.y"
                          {
        /* Expr = Expr - Term */

        // 创建一个AST_OP_SUB类型的中间节点，孩子为Expr($1)和Term($3)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_SUB, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
    }
#line 1830 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 65: /* MulExp: MinusExp  */
#line 403 "/root/calculator/frontend/flexbison/Calculator.y"
                  {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1838 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 66: /* MulExp: MulExp T_MUL MinusExp  */
#line 406 "/root/calculator/frontend/flexbison/Calculator.y"
                                {
      	/* Expr = Expr * Term */

		// 创建一个AST_OP_MUL类型的中间节点，孩子为Expr($1)和Term($3)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_MUL, (yyvsp[-2].node), (yyvsp[0].node), nullptr);

	}
#line 1850 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 67: /* MulExp: MulExp T_DIV MinusExp  */
#line 413 "/root/calculator/frontend/flexbison/Calculator.y"
                                {
        /* Expr = Expr / Term */

		// 创建一个AST_OP_DIV类型的中间节点，孩子为Expr($1)和Term($3)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_DIV, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 1861 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 68: /* MulExp: MulExp T_MOD MinusExp  */
#line 419 "/root/calculator/frontend/flexbison/Calculator.y"
                            {
        /* Expr = Expr % Term */

		// 创建一个AST_OP_MOD类型的中间节点，孩子为Expr($1)和Term($3)
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_MOD, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
    }
#line 1872 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 69: /* MinusExp: T_SUB UnaryExp  */
#line 428 "/root/calculator/frontend/flexbison/Calculator.y"
                         {
        /* Expr = -Term */

        // 创建一个AST_OP_SUB类型的中间节点，孩子为Term($2)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_SUB, (yyvsp[0].node), nullptr);
    }
#line 1883 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 70: /* MinusExp: T_NOT UnaryExp  */
#line 434 "/root/calculator/frontend/flexbison/Calculator.y"
                         {
		/* Expr = !Term */

        // 创建一个AST_OP_NOT类型的中间节点，孩子为Term($2)
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_NOT, (yyvsp[0].node), nullptr);
	}
#line 1894 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 71: /* MinusExp: UnaryExp  */
#line 440 "/root/calculator/frontend/flexbison/Calculator.y"
                   {
        /* Expr = Term */
        (yyval.node) = (yyvsp[0].node);
    }
#line 1903 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 72: /* UnaryExp: PrimaryExp  */
#line 446 "/root/calculator/frontend/flexbison/Calculator.y"
                      {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1911 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 73: /* UnaryExp: T_ID '(' ')'  */
#line 449 "/root/calculator/frontend/flexbison/Calculator.y"
                   {
        // 用户自定义的不含实参的函数调用
        (yyval.node) = create_func_call((yyvsp[-2].var_id).lineno, (yyvsp[-2].var_id).id, nullptr);
    }
#line 1920 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 74: /* UnaryExp: T_ID '(' RealParamList ')'  */
#line 453 "/root/calculator/frontend/flexbison/Calculator.y"
                                 {
        // 用户自定义的含有实参的参数调用
        (yyval.node) = create_func_call((yyvsp[-3].var_id).lineno, (yyvsp[-3].var_id).id, (yyvsp[-1].node));
    }
#line 1929 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 75: /* PrimaryExp: '(' Expr ')'  */
#line 459 "/root/calculator/frontend/flexbison/Calculator.y"
                           {
        /* PrimaryExp = Expr */
        (yyval.node) = (yyvsp[-1].node);
    }
#line 1938 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 76: /* PrimaryExp: T_DIGIT  */
#line 463 "/root/calculator/frontend/flexbison/Calculator.y"
              {
        // 无符号整数识别

        // 终结符作为抽象语法树的叶子节点进行创建
        (yyval.node) = new_ast_leaf_node(digit_int_attr{(yyvsp[0].integer_num).val, (yyvsp[0].integer_num).lineno});
    }
#line 1949 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 77: /* PrimaryExp: LVal  */
#line 469 "/root/calculator/frontend/flexbison/Calculator.y"
            {
        // 左值
        (yyval.node) = (yyvsp[0].node);
    }
#line 1958 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 78: /* LVal: T_ID  */
#line 475 "/root/calculator/frontend/flexbison/Calculator.y"
            {
        // 终结符作为抽象语法树的叶子节点进行创建
        (yyval.node) = new_ast_leaf_node(var_id_attr{(yyvsp[0].var_id).id, (yyvsp[0].var_id).lineno});

		// 对于字符型字面量的字符串空间需要释放，因词法用到了strdup进行了字符串复制
		free((yyvsp[0].var_id).id);
    }
#line 1970 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 79: /* RealParamList: Expr  */
#line 484 "/root/calculator/frontend/flexbison/Calculator.y"
                     {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_FUNC_REAL_PARAMS, (yyvsp[0].node));
    }
#line 1978 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 80: /* RealParamList: RealParamList ',' Expr  */
#line 487 "/root/calculator/frontend/flexbison/Calculator.y"
                             {
        (yyval.node) = insert_ast_node((yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1986 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;


#line 1990 "/root/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"

      default: break;
    }
  /* User semantic actions sometimes alter yychar, and that requires
     that yytoken be updated with the new translation.  We take the
     approach of translating immediately before every use of yytoken.
     One alternative is translating here after every semantic action,
     but that translation would be missed if the semantic action invokes
     YYABORT, YYACCEPT, or YYERROR immediately after altering yychar or
     if it invokes YYBACKUP.  In the case of YYABORT or YYACCEPT, an
     incorrect destructor might then be invoked immediately.  In the
     case of YYERROR or YYBACKUP, subsequent parser actions might lead
     to an incorrect destructor call or verbose syntax error message
     before the lookahead is translated.  */
  YY_SYMBOL_PRINT ("-> $$ =", YY_CAST (yysymbol_kind_t, yyr1[yyn]), &yyval, &yyloc);

  YYPOPSTACK (yylen);
  yylen = 0;

  *++yyvsp = yyval;

  /* Now 'shift' the result of the reduction.  Determine what state
     that goes to, based on the state we popped back to and the rule
     number reduced by.  */
  {
    const int yylhs = yyr1[yyn] - YYNTOKENS;
    const int yyi = yypgoto[yylhs] + *yyssp;
    yystate = (0 <= yyi && yyi <= YYLAST && yycheck[yyi] == *yyssp
               ? yytable[yyi]
               : yydefgoto[yylhs]);
  }

  goto yynewstate;


/*--------------------------------------.
| yyerrlab -- here on detecting error.  |
`--------------------------------------*/
yyerrlab:
  /* Make sure we have latest lookahead translation.  See comments at
     user semantic actions for why this is necessary.  */
  yytoken = yychar == YYEMPTY ? YYSYMBOL_YYEMPTY : YYTRANSLATE (yychar);
  /* If not already recovering from an error, report this error.  */
  if (!yyerrstatus)
    {
      ++yynerrs;
      yyerror (YY_("syntax error"));
    }

  if (yyerrstatus == 3)
    {
      /* If just tried and failed to reuse lookahead token after an
         error, discard it.  */

      if (yychar <= YYEOF)
        {
          /* Return failure if at end of input.  */
          if (yychar == YYEOF)
            YYABORT;
        }
      else
        {
          yydestruct ("Error: discarding",
                      yytoken, &yylval);
          yychar = YYEMPTY;
        }
    }

  /* Else will try to reuse lookahead token after shifting the error
     token.  */
  goto yyerrlab1;


/*---------------------------------------------------.
| yyerrorlab -- error raised explicitly by YYERROR.  |
`---------------------------------------------------*/
yyerrorlab:
  /* Pacify compilers when the user code never invokes YYERROR and the
     label yyerrorlab therefore never appears in user code.  */
  if (0)
    YYERROR;
  ++yynerrs;

  /* Do not reclaim the symbols of the rule whose action triggered
     this YYERROR.  */
  YYPOPSTACK (yylen);
  yylen = 0;
  YY_STACK_PRINT (yyss, yyssp);
  yystate = *yyssp;
  goto yyerrlab1;


/*-------------------------------------------------------------.
| yyerrlab1 -- common code for both syntax error and YYERROR.  |
`-------------------------------------------------------------*/
yyerrlab1:
  yyerrstatus = 3;      /* Each real token shifted decrements this.  */

  /* Pop stack until we find a state that shifts the error token.  */
  for (;;)
    {
      yyn = yypact[yystate];
      if (!yypact_value_is_default (yyn))
        {
          yyn += YYSYMBOL_YYerror;
          if (0 <= yyn && yyn <= YYLAST && yycheck[yyn] == YYSYMBOL_YYerror)
            {
              yyn = yytable[yyn];
              if (0 < yyn)
                break;
            }
        }

      /* Pop the current state because it cannot handle the error token.  */
      if (yyssp == yyss)
        YYABORT;


      yydestruct ("Error: popping",
                  YY_ACCESSING_SYMBOL (yystate), yyvsp);
      YYPOPSTACK (1);
      yystate = *yyssp;
      YY_STACK_PRINT (yyss, yyssp);
    }

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END


  /* Shift the error token.  */
  YY_SYMBOL_PRINT ("Shifting", YY_ACCESSING_SYMBOL (yyn), yyvsp, yylsp);

  yystate = yyn;
  goto yynewstate;


/*-------------------------------------.
| yyacceptlab -- YYACCEPT comes here.  |
`-------------------------------------*/
yyacceptlab:
  yyresult = 0;
  goto yyreturnlab;


/*-----------------------------------.
| yyabortlab -- YYABORT comes here.  |
`-----------------------------------*/
yyabortlab:
  yyresult = 1;
  goto yyreturnlab;


/*-----------------------------------------------------------.
| yyexhaustedlab -- YYNOMEM (memory exhaustion) comes here.  |
`-----------------------------------------------------------*/
yyexhaustedlab:
  yyerror (YY_("memory exhausted"));
  yyresult = 2;
  goto yyreturnlab;


/*----------------------------------------------------------.
| yyreturnlab -- parsing is finished, clean up and return.  |
`----------------------------------------------------------*/
yyreturnlab:
  if (yychar != YYEMPTY)
    {
      /* Make sure we have latest lookahead translation.  See comments at
         user semantic actions for why this is necessary.  */
      yytoken = YYTRANSLATE (yychar);
      yydestruct ("Cleanup: discarding lookahead",
                  yytoken, &yylval);
    }
  /* Do not reclaim the symbols of the rule whose action triggered
     this YYABORT or YYACCEPT.  */
  YYPOPSTACK (yylen);
  YY_STACK_PRINT (yyss, yyssp);
  while (yyssp != yyss)
    {
      yydestruct ("Cleanup: popping",
                  YY_ACCESSING_SYMBOL (+*yyssp), yyvsp);
      YYPOPSTACK (1);
    }
#ifndef yyoverflow
  if (yyss != yyssa)
    YYSTACK_FREE (yyss);
#endif

  return yyresult;
}

#line 491 "/root/calculator/frontend/flexbison/Calculator.y"


// 语法识别错误要调用函数的定义
void yyerror(char * msg)
{
    printf("Line %d: %s\n", yylineno, msg);
}
